# Generated by Django 4.1.2 on 2022-10-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='num_bathrooms',
            field=models.IntegerField(default=555, verbose_name=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='num_bedrooms',
            field=models.IntegerField(default=26, verbose_name=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.IntegerField(default=23, verbose_name=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='square_footage',
            field=models.IntegerField(default=233, verbose_name=1),
            preserve_default=False,
        ),
    ]
